from __future__ import annotations

from pathlib import Path

from skill_manager.application.packages import list_package_dirs, load_package_meta
from skill_manager.application.skills.store import SkillStore
from skill_manager.atomic_files import atomic_write_text

from .model import (
    AgentCompileError,
    AgentDefinition,
    AgentParseError,
    CompiledAgentArtifact,
    ResolvedSkill,
)
from .parser import parse_agent_file

GENERATED_MARKER = "skill-manager:generated"

# Harnesses the compiler can target today, with the constraints each one can
# actually enforce. Anything an agent asks for beyond this surfaces as a
# degradation note instead of being silently dropped.
COMPILE_TARGETS = ("claude",)


class AgentsService:
    def __init__(self, packages_root: Path, skills_store: SkillStore, home: Path) -> None:
        self.packages_root = packages_root
        self.skills_store = skills_store
        self.home = home

    def scan(self) -> tuple[tuple[AgentDefinition, ...], tuple[str, ...]]:
        agents: list[AgentDefinition] = []
        issues: list[str] = []
        for pkg_dir in list_package_dirs(self.packages_root):
            try:
                meta = load_package_meta(pkg_dir / "package.json")
            except Exception as error:
                issues.append(f"Unreadable package.json in {pkg_dir.name}: {error}")
                continue
            if not meta.active:
                continue
            agents_dir = pkg_dir / "agents"
            if not agents_dir.is_dir():
                continue
            for path in sorted(agents_dir.glob("*.md")):
                try:
                    agents.append(parse_agent_file(path, package_slug=meta.slug))
                except AgentParseError as error:
                    issues.append(f"Invalid agent {meta.slug}/{path.stem}: {error}")
        return tuple(agents), tuple(issues)

    def get(self, agent_ref: str) -> AgentDefinition | None:
        agents, _ = self.scan()
        for agent in agents:
            if agent.ref == agent_ref:
                return agent
        return None

    def compile(self, agent: AgentDefinition, harness: str) -> CompiledAgentArtifact:
        if harness not in COMPILE_TARGETS:
            raise AgentCompileError(
                f"unsupported compile target: {harness} (supported: {', '.join(COMPILE_TARGETS)})"
            )
        resolved = self._resolve_skills(agent)
        return self._compile_claude(agent, resolved)

    def write_artifact(self, artifact: CompiledAgentArtifact) -> None:
        target = artifact.target_path
        if target.exists() and GENERATED_MARKER not in target.read_text(encoding="utf-8"):
            raise AgentCompileError(
                f"refusing to overwrite {target}: existing file was not generated by skill-manager"
            )
        target.parent.mkdir(parents=True, exist_ok=True)
        atomic_write_text(target, artifact.content)

    def _resolve_skills(self, agent: AgentDefinition) -> tuple[ResolvedSkill, ...]:
        scan = self.skills_store.scan()
        by_alias: dict[str, ResolvedSkill] = {}
        for observation in scan.packages:
            pkg = observation.package
            alias = f"{observation.owning_package_slug}/{pkg.root_path.name}"
            by_alias[alias] = ResolvedSkill(
                alias=alias,
                declared_name=pkg.declared_name,
                revision=pkg.revision,
                document=(pkg.root_path / "SKILL.md").read_text(encoding="utf-8"),
            )
        resolved: list[ResolvedSkill] = []
        missing: list[str] = []
        for alias in agent.skills:
            if alias in by_alias:
                resolved.append(by_alias[alias])
            else:
                missing.append(alias)
        if missing:
            raise AgentCompileError(
                f"agent {agent.ref} references unknown skills: {', '.join(missing)}"
            )
        return tuple(resolved)

    def _compile_claude(
        self, agent: AgentDefinition, resolved: tuple[ResolvedSkill, ...]
    ) -> CompiledAgentArtifact:
        overrides = dict(agent.harness_overrides.get("claude", {}))
        degradations: list[str] = []
        if agent.tools_denied:
            degradations.append(
                "claude: tool deny-lists are advisory only — Claude Code agents enforce "
                f"an allowlist; denied tools ({', '.join(agent.tools_denied)}) are stated "
                "in the prompt but not enforced by the harness"
            )
        if agent.mcps:
            degradations.append(
                "claude: MCP capabilities are not compiled in v1 — configure "
                f"({', '.join(agent.mcps)}) through the MCP workspace"
            )
        frontmatter_lines = [
            "---",
            f"name: {agent.slug}",
            f"description: {agent.description or agent.name}",
        ]
        if agent.tools_allowed:
            frontmatter_lines.append(f"tools: {', '.join(agent.tools_allowed)}")
        if overrides.get("model"):
            frontmatter_lines.append(f"model: {overrides['model']}")
        if overrides.get("reasoning_effort"):
            frontmatter_lines.append(f"reasoning_effort: {overrides['reasoning_effort']}")
        frontmatter_lines.append("---")
        pinned = ",".join(f"{skill.alias}@{skill.revision[:12]}" for skill in resolved)
        provenance = (
            f"<!-- {GENERATED_MARKER} agent={agent.ref} hash={agent.fingerprint[:12]}"
            + (f" skills={pinned}" if pinned else "")
            + " -->"
        )
        sections = ["\n".join(frontmatter_lines), provenance, agent.prompt]
        if agent.tools_denied:
            sections.append(
                "## Tool restrictions\n\nDo not use these tools: "
                + ", ".join(agent.tools_denied)
            )
        for skill in resolved:
            sections.append(
                f"## Skill: {skill.declared_name} ({skill.alias})\n\n{_strip_frontmatter(skill.document)}"
            )
        content = "\n\n".join(section for section in sections if section) + "\n"
        return CompiledAgentArtifact(
            agent_ref=agent.ref,
            harness="claude",
            target_path=self.home / ".claude" / "agents" / f"{agent.slug}.md",
            content=content,
            resolved_skills=resolved,
            degradations=tuple(degradations),
        )


def _strip_frontmatter(document: str) -> str:
    lines = document.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        return document.strip()
    for index, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            return "".join(lines[index + 1 :]).strip()
    return document.strip()


__all__ = ["AgentsService", "COMPILE_TARGETS", "GENERATED_MARKER"]
