from __future__ import annotations

from pathlib import Path

import io
from ruamel.yaml import YAML

from skill_manager.application.skills.store import SkillStore
from skill_manager.atomic_files import atomic_write_text

from .model import (
    AgentCompileError,
    AgentDefinition,
    AgentParseError,
    CompiledAgentArtifact,
    ResolvedSkill,
)
from .parser import parse_agent_file, split_frontmatter

GENERATED_MARKER = "skill-manager:generated"

# Harnesses the compiler can target today, with the constraints each one can
# actually enforce. Anything an agent asks for beyond this surfaces as a
# degradation note instead of being silently dropped.
COMPILE_TARGETS = ("claude", "cursor", "codex")


class AgentsService:
    def __init__(self, agents_root: Path, skills_store: SkillStore, home: Path) -> None:
        self.agents_root = agents_root
        self.skills_store = skills_store
        self.home = home

    def scan(self) -> tuple[tuple[AgentDefinition, ...], tuple[str, ...]]:
        agents: list[AgentDefinition] = []
        issues: list[str] = []
        if not self.agents_root.is_dir():
            return (), ()
        for path in sorted(self.agents_root.glob("*.md")):
            try:
                agents.append(parse_agent_file(path))
            except AgentParseError as error:
                issues.append(f"Invalid agent {path.stem}: {error}")
        return tuple(agents), tuple(issues)

    def get(self, agent_ref: str) -> AgentDefinition | None:
        agents, _ = self.scan()
        for agent in agents:
            if agent.ref == agent_ref:
                return agent
        return None

    def save_agent(
        self,
        agent_ref: str,
        *,
        name: str | None = None,
        description: str | None = None,
        skills: list[str] | None = None,
        mcps: list[str] | None = None,
    ) -> AgentDefinition:
        agent = self.get(agent_ref)
        if agent is None:
            raise ValueError(f"Agent not found: {agent_ref}")

        path = agent.path
        document = path.read_text(encoding="utf-8")
        metadata, body = split_frontmatter(document)

        if name is not None:
            metadata["name"] = name
        if description is not None:
            metadata["description"] = description

        if "capabilities" not in metadata or not isinstance(metadata["capabilities"], dict):
            metadata["capabilities"] = {}

        if skills is not None:
            metadata["capabilities"]["skills"] = list(skills)
        if mcps is not None:
            metadata["capabilities"]["mcps"] = list(mcps)

        yaml = YAML()
        yaml.default_flow_style = False
        stream = io.StringIO()
        yaml.dump(metadata, stream)
        new_frontmatter = stream.getvalue().strip()

        new_content = f"---\n{new_frontmatter}\n---\n\n{body.lstrip()}"
        atomic_write_text(path, new_content)

        return parse_agent_file(path)


    def compile(
        self, agent: AgentDefinition, harness: str, *, project_dir: Path | None = None
    ) -> CompiledAgentArtifact:
        if harness not in COMPILE_TARGETS:
            raise AgentCompileError(
                f"unsupported compile target: {harness} (supported: {', '.join(COMPILE_TARGETS)})"
            )
        resolved = self._resolve_skills(agent)
        if harness == "claude":
            return self._compile_claude(agent, resolved)
        if harness == "cursor":
            return self._compile_cursor(agent, resolved, project_dir)
        return self._compile_codex(agent, resolved)

    def write_artifact(self, artifact: CompiledAgentArtifact) -> None:
        target = artifact.target_path
        if target.exists() and GENERATED_MARKER not in target.read_text(encoding="utf-8"):
            raise AgentCompileError(
                f"refusing to overwrite {target}: existing file was not generated by skill-manager"
            )
        target.parent.mkdir(parents=True, exist_ok=True)
        atomic_write_text(target, artifact.content)

    def _resolve_skills(self, agent: AgentDefinition) -> tuple[ResolvedSkill, ...]:
        scan = self.skills_store.scan()
        by_alias: dict[str, ResolvedSkill] = {}
        for observation in scan.packages:
            pkg = observation.package
            alias = pkg.root_path.name
            by_alias[alias] = ResolvedSkill(
                alias=alias,
                declared_name=pkg.declared_name,
                revision=pkg.revision,
                document=(pkg.root_path / "SKILL.md").read_text(encoding="utf-8"),
            )
        resolved: list[ResolvedSkill] = []
        missing: list[str] = []
        for alias in agent.skills:
            if alias in by_alias:
                resolved.append(by_alias[alias])
            else:
                missing.append(alias)
        if missing:
            raise AgentCompileError(
                f"agent {agent.ref} references unknown skills: {', '.join(missing)}"
            )
        return tuple(resolved)

    def _compile_claude(
        self, agent: AgentDefinition, resolved: tuple[ResolvedSkill, ...]
    ) -> CompiledAgentArtifact:
        overrides = dict(agent.harness_overrides.get("claude", {}))
        degradations: list[str] = []
        if agent.tools_denied:
            degradations.append(
                "claude: tool deny-lists are advisory only — Claude Code agents enforce "
                f"an allowlist; denied tools ({', '.join(agent.tools_denied)}) are stated "
                "in the prompt but not enforced by the harness"
            )
        if agent.mcps:
            degradations.append(
                "claude: MCP capabilities are not compiled in v1 — configure "
                f"({', '.join(agent.mcps)}) through the MCP workspace"
            )
        frontmatter_lines = [
            "---",
            f"name: {agent.slug}",
            f"description: {agent.description or agent.name}",
        ]
        if agent.tools_allowed:
            frontmatter_lines.append(f"tools: {', '.join(agent.tools_allowed)}")
        if overrides.get("model"):
            frontmatter_lines.append(f"model: {overrides['model']}")
        if overrides.get("reasoning_effort"):
            frontmatter_lines.append(f"reasoning_effort: {overrides['reasoning_effort']}")
        frontmatter_lines.append("---")
        content = _render_artifact(
            "\n".join(frontmatter_lines), _provenance(agent, resolved), agent, resolved
        )
        return CompiledAgentArtifact(
            agent_ref=agent.ref,
            harness="claude",
            target_path=self.home / ".claude" / "agents" / f"{agent.slug}.md",
            content=content,
            resolved_skills=resolved,
            degradations=tuple(degradations),
        )

    def _compile_cursor(
        self,
        agent: AgentDefinition,
        resolved: tuple[ResolvedSkill, ...],
        project_dir: Path | None,
    ) -> CompiledAgentArtifact:
        if project_dir is None:
            raise AgentCompileError(
                "cursor rules are project-scoped: pass projectDir to compile for cursor"
            )
        overrides = dict(agent.harness_overrides.get("cursor", {}))
        degradations: list[str] = []
        if agent.tools_allowed or agent.tools_denied:
            degradations.append(
                "cursor: tool allow/deny lists are advisory only — Cursor rules cannot "
                "enforce tool restrictions; they are stated in the rule text"
            )
        if overrides.get("model"):
            degradations.append(
                f"cursor: model override ({overrides['model']}) is not settable via a "
                "rules file — select the model in Cursor itself"
            )
        if overrides.get("reasoning_effort"):
            degradations.append(
                "cursor: reasoning_effort is not settable via a rules file"
            )
        if agent.mcps:
            degradations.append(
                "cursor: MCP capabilities are not compiled in v1 — configure "
                f"({', '.join(agent.mcps)}) through the MCP workspace"
            )
        frontmatter = "\n".join(
            [
                "---",
                f"description: {agent.description or agent.name}",
                "alwaysApply: true",
                "---",
            ]
        )
        content = _render_artifact(frontmatter, _provenance(agent, resolved), agent, resolved)
        return CompiledAgentArtifact(
            agent_ref=agent.ref,
            harness="cursor",
            target_path=project_dir / ".cursor" / "rules" / f"skill-manager.{agent.slug}.mdc",
            content=content,
            resolved_skills=resolved,
            degradations=tuple(degradations),
        )

    def _compile_codex(
        self, agent: AgentDefinition, resolved: tuple[ResolvedSkill, ...]
    ) -> CompiledAgentArtifact:
        overrides = dict(agent.harness_overrides.get("codex", {}))
        degradations: list[str] = [
            "codex: compiled as a custom prompt (~/.codex/prompts) invoked as "
            f"/{agent.slug}, not a persistent persona — Codex has no agent-definition "
            "file skill-manager can own without overwriting user AGENTS.md"
        ]
        if agent.tools_allowed or agent.tools_denied:
            degradations.append(
                "codex: tool allow/deny lists are advisory only — not enforced by Codex"
            )
        if overrides.get("model"):
            degradations.append(
                f"codex: model override ({overrides['model']}) is not compiled — set it "
                "via a Codex profile in config.toml"
            )
        if agent.mcps:
            degradations.append(
                "codex: MCP capabilities are not compiled in v1 — configure "
                f"({', '.join(agent.mcps)}) through the MCP workspace"
            )
        content = _render_artifact(None, _provenance(agent, resolved), agent, resolved)
        return CompiledAgentArtifact(
            agent_ref=agent.ref,
            harness="codex",
            target_path=self.home / ".codex" / "prompts" / f"{agent.slug}.md",
            content=content,
            resolved_skills=resolved,
            degradations=tuple(degradations),
        )


def _provenance(agent: AgentDefinition, resolved: tuple[ResolvedSkill, ...]) -> str:
    pinned = ",".join(f"{skill.alias}@{skill.revision[:12]}" for skill in resolved)
    return (
        f"<!-- {GENERATED_MARKER} agent={agent.ref} hash={agent.fingerprint[:12]}"
        + (f" skills={pinned}" if pinned else "")
        + " -->"
    )


def _render_artifact(
    frontmatter: str | None,
    provenance: str,
    agent: AgentDefinition,
    resolved: tuple[ResolvedSkill, ...],
) -> str:
    sections = [frontmatter, provenance, agent.prompt]
    if agent.tools_denied:
        sections.append(
            "## Tool restrictions\n\nDo not use these tools: " + ", ".join(agent.tools_denied)
        )
    for skill in resolved:
        sections.append(
            f"## Skill: {skill.declared_name} ({skill.alias})\n\n{_strip_frontmatter(skill.document)}"
        )
    return "\n\n".join(section for section in sections if section) + "\n"


def _strip_frontmatter(document: str) -> str:
    lines = document.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        return document.strip()
    for index, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            return "".join(lines[index + 1 :]).strip()
    return document.strip()


__all__ = ["AgentsService", "COMPILE_TARGETS", "GENERATED_MARKER"]
